name: ec2 deployment

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies and run migrations
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          python manage.py migrate

      - name: Build React frontend
        run: |
          cd frontend
          npm update
          npm install
          npm run eject -y

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.EC2_USERNAME }}
          host: ${{ secrets.EC2_HOST }}
           
        with:
          script: |
            touch testing.txt
