name: ec2 deployment

on:
 push:
   branches:
      -first
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies and run migrations
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          python manage.py migrate

      - name: Build React frontend
        run: |
          cd frontend
          npm update
          npm install
          npm run eject

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          run : echo "${{ secrets.EC2_HOST }}"
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd real-estate
            git pull origin first
            sudo systemctl stop apache2
            python manage.py collectstatic --noinput
            sudo systemctl start apache2
